### ISSUE TITLE
Local wdio test gives: javascript error: Failed to read the 'sessionStorage' property from 'Window': Access is denied for this document.

### ISSUE THREAD

**Issue by ksubramanian2** [chmanie/wdio-intercept-service#113]
Using Chromedriver. 
Any browser settings needed or time delay needed? 
I am not blocking any third party cookies 

[chrome 87.0.4280.88 mac os x #0-0] JavaScript stack:
[chrome 87.0.4280.88 mac os x #0-0] Error: Failed to read the 'sessionStorage' property from 'Window': Access is denied for this document.
[chrome 87.0.4280.88 mac os x #0-0]     at setup (eval at executeAsyncScript (:556:26), <anonymous>:13:16)
[chrome 87.0.4280.88 mac os x #0-0]     at eval (eval at executeAsyncScript (:556:26), <anonymous>:191:6)
[chrome 87.0.4280.88 mac os x #0-0]     at eval (eval at executeAsyncScript (:556:26), <anonymous>:192:4)
[chrome 87.0.4280.88 mac os x #0-0]     at executeAsyncScript (<anonymous>:556:47)
[chrome 87.0.4280.88 mac os x #0-0]     at <anonymous>:571:29
[chrome 87.0.4280.88 mac os x #0-0]     at callFunction (<anonymous>:450:22)
[chrome 87.0.4280.88 mac os x #0-0]     at <anonymous>:464:23
[chrome 87.0.4280.88 mac os x #0-0]     at <anonymous>:465:3
[chrome 87.0.4280.88 mac os x #0-0]   (Session info: chrome=87.0.4280.88)
[chrome 87.0.4280.88 mac os x #0-0]     at processTicksAndRejections (internal/process/task_queues.js:85:5)
[chrome 87.0.4280.88 mac os x #0-0]     at WebdriverAjax.setup (/Users/ksubramanian3/Documents/projects/tracking-core/node_modules/wdio-intercept-service/index.js:41:22)
[chrome 87.0.4280.88 mac os x #0-0]     at Browser.next [as setupInterceptor] (/Users/ksubramanian3/Documents/projects/tracking-core/node_modules/@wdio/utils/build/monad.js:95:33)
[chrome 87.0.4280.88 mac os x #0-0]     at Context.<anonymous> (/Users/ksubramanian3/Documents/projects/tracking-core/tests/integration/tracking-core.selenium.js:199:13)

**Comment by ksubramanian2** [comment]
After I put in a delay between browser.url() and browser.setupInterceptor() like below, I could see that the page showed a security dialog box about not being able to verify the site certificate. So, not an interceptor problem.
    browser.url(url);
    browser.$('h1').waitForDisplayed();
    browser.pause();
    browser.setupInterceptor();
