### ISSUE TITLE
error TS2339: Property 'setupInterceptor' does not exist on type 'BrowserObject'.

### ISSUE THREAD

**Issue by griou** [chmanie/wdio-intercept-service#64]
Hello,

It looks like the service is not working with typescript, is their a way to fix it ?

steps to reproduce :
```shell
# clone a typescript boilerplate
$ git clone git@github.com:jpolley/WebdriverIO_v5_TypeScript.git 
$ cd WebdriverIO_v5_TypeScript

# install dependencies
$ npm i 

# check this spec is working
$ npm test -- --spec dropdown.spec.ts 

# install intercept service
$ npm i --save-dev wdio-intercept-service

# add intercept to wdio conf, ie. `services: ['selenium-standalone', 'intercept']`
$ sed -i.bak -E "s/(services: \['selenium-standalone')\]/\1, 'intercept'\]/" wdio.conf.js
# add an intercept step to a spec ie. `return browser.url('/dropdown').setupInterceptor();`
$ sed -i.bak -E "s/(return browser.url\('/dropdown'\));/\1.setupInterceptor();/" src/pages/DropdownPage.ts

# run it, it's not working :(
$ npm test -- --spec dropdown.spec.ts 
npm info it worked if it ends with ok
npm verb cli [
npm verb cli   '/usr/local/Cellar/node/12.8.0/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'test',
npm verb cli   '--',
npm verb cli   '--spec',
npm verb cli   'src/pages/DropdownPage.ts'
npm verb cli ]
npm info using npm@6.10.3
npm info using node@v12.8.0
npm verb run-script [ 'pretest', 'test', 'posttest' ]
npm info lifecycle webdriverio_v5_typescript@1.0.0~pretest: webdriverio_v5_typescript@1.0.0
npm info lifecycle webdriverio_v5_typescript@1.0.0~test: webdriverio_v5_typescript@1.0.0

> webdriverio_v5_typescript@1.0.0 test /Users/user/WebdriverIO_v5_TypeScript
> wdio "--spec" "src/pages/DropdownPage.ts"


Execution of 1 spec files started at 2020-01-20T22:36:48.267Z

2020-01-20T22:36:48.269Z DEBUG @wdio/utils:initialiseServices: initialise wdio service "selenium-standalone"
2020-01-20T22:36:48.304Z DEBUG @wdio/utils:initialiseServices: initialise wdio service "intercept"
2020-01-20T22:36:48.306Z INFO @wdio/cli:launcher: Run onPrepare hook
2020-01-20T22:36:49.568Z INFO @wdio/local-runner: Start worker 0-0 with arg: --spec,src/pages/DropdownPage.ts
[0-0] 2020-01-20T22:36:49.779Z INFO @wdio/local-runner: Run worker command: run
[0-0] RUNNING in chrome - /src/pages/DropdownPage.ts
[0-0] 2020-01-20T22:36:49.947Z DEBUG @wdio/utils:initialiseServices: initialise wdio service "intercept"
[0-0] 2020-01-20T22:36:49.948Z DEBUG @wdio/local-runner:utils: init remote session
[0-0] 2020-01-20T22:36:49.949Z INFO webdriverio: Initiate new session using the webdriver protocol
[0-0] 2020-01-20T22:36:49.950Z INFO webdriver: [POST] http://127.0.0.1:4444/wd/hub/session
[0-0] 2020-01-20T22:36:49.950Z INFO webdriver: DATA {
  capabilities: { alwaysMatch: { browserName: 'chrome' }, firstMatch: [ {} ] },
  desiredCapabilities: { browserName: 'chrome' }
}
[0-0] 2020-01-20T22:36:52.350Z ERROR @wdio/runner: TSError: ⨯ Unable to compile TypeScript:
src/pages/DropdownPage.ts(5,41): error TS2339: Property 'setupInterceptor' does not exist on type 'void'.

    at createTSError (/Users/user/WebdriverIO_v5_TypeScript/node_modules/ts-node/src/index.ts:261:12)
    at getOutput (/Users/user/WebdriverIO_v5_TypeScript/node_modules/ts-node/src/index.ts:367:40)
    at Object.compile (/Users/user/WebdriverIO_v5_TypeScript/node_modules/ts-node/src/index.ts:558:11)
    at Module.m._compile (/Users/user/WebdriverIO_v5_TypeScript/node_modules/ts-node/src/index.ts:439:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/user/WebdriverIO_v5_TypeScript/node_modules/ts-node/src/index.ts:442:12)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
    at Module.require (internal/modules/cjs/loader.js:771:19)
    at require (internal/modules/cjs/helpers.js:68:18)
[0-0] Error: ⨯ Unable to compile TypeScript:
src/pages/DropdownPage.ts(5,41): error TS2339: Property 'setupInterceptor' does not exist on type 'void'.

[0-0] 2020-01-20T22:36:52.373Z INFO webdriver: COMMAND deleteSession()
[0-0] 2020-01-20T22:36:52.373Z INFO webdriver: [DELETE] http://127.0.0.1:4444/wd/hub/session/f3c1a49088665b5cb89c5ce92b87383d
2020-01-20T22:36:52.553Z DEBUG @wdio/local-runner: Runner 0-0 finished with exit code 1
[0-0] FAILED in chrome - /src/pages/DropdownPage.ts
2020-01-20T22:36:52.554Z INFO @wdio/cli:launcher: Run onComplete hook
2020-01-20T22:36:52.554Z INFO @wdio/selenium-standalone-service: shutting down all browsers

Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:04 

2020-01-20T22:36:52.555Z INFO @wdio/local-runner: Shutting down spawned worker
2020-01-20T22:36:52.807Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2020-01-20T22:36:52.808Z INFO @wdio/local-runner: shutting down
npm verb lifecycle webdriverio_v5_typescript@1.0.0~test: unsafe-perm in lifecycle true
npm verb lifecycle webdriverio_v5_typescript@1.0.0~test: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/user/WebdriverIO_v5_TypeScript/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands
npm verb lifecycle webdriverio_v5_typescript@1.0.0~test: CWD: /Users/user/WebdriverIO_v5_TypeScript
npm info lifecycle webdriverio_v5_typescript@1.0.0~test: Failed to exec test script
npm ERR! Test failed.  See above for more details.
npm verb exit [ 1, true ]
npm timing npm Completed in 5456ms
npm verb code 1
```
Thanks for any help.

**Comment by chmanie** [comment]
I'd have to look into it but as it looks to me that's only possible by providing TS type additions (I'm happy for any PR here 🙂 )

**Comment by li-guillaumeriou** [comment]
Thanks for your feedback, I have no idea how to fix it, but I'll keep searching and if I find something, I will send a PR.

**Comment by rvenk693** [comment]
Could this help ? I am running into the same problem using typescript and the intercept-service https://www.credera.com/blog/technology-solutions/typescript-adding-custom-type-definitions-for-existing-libraries/

**Comment by chmanie** [comment]
We’d have to make TS aware of that plugin somehow. Because we’re monkey patching the ‘browser’ object. I’ll look into it today as this seems to be blocking!

**Comment by chmanie** [comment]
v4.0.0 has TS support. Let me know how it works for you (if there are problems, just open another issue)

**Comment by rvenk693** [comment]
@chmanie - thank you it worked , also to confirm we are only able to intercept xhr requests other requests are not interecepted correct or browser.getRequests does not provide all requests made only xhr ones ?

**Comment by chmanie** [comment]
Yes, it will intercept requests made via xhr and `fetch`

**Comment by yhtang68** [comment]
Hello, 
@chmanie 
I'm running into this same issue 
Property 'setupInterceptor' does not exist on type 'BrowserObject'.ts(2339)
on 
"wdio-intercept-service": "^4.1.3",
"_from": "webdriverio@6.7.3",

What's the fix here?

Thank you

**Comment by yhtang68** [comment]
https://stackoverflow.com/questions/59132068/property-setupinterceptor-does-not-exist-on-type-browserobject
this seems a fix.

Add wdio-intercept-service in your tsconfig.json's types section

**Comment by chmanie** [comment]
Happy you could resolve it!

The [Readme](https://github.com/webdriverio-community/wdio-intercept-service#typescript-support) also has an example 😉
